### ISSUE TITLE
［Bug］使用传分token HTTP返回400但传分仍然成功

### ISSUE THREAD

**Issue by Dreamail** [Diving-Fish/maimaidx-prober#112]

**Comment by Dreamail** [comment]
https://github.com/Diving-Fish/maimaidx-prober/blob/main/database/app.py#L80-L80

猜测是因为解析上传数据时报错，但被try except捕捉返回错误

**Comment by Dreamail** [comment]
btw,可以要个dev token嘛👀

**Comment by Diving-Fish** [comment]
> btw,可以要个dev token嘛👀

可以加我q 2300756578或者加开发者群 605800479
