### ISSUE TITLE
proxy1.3.3上传的达成率只剩下一位小数,后边三位固定000?

### ISSUE THREAD

**Issue by kuresaru** [Diving-Fish/maimaidx-prober#118]
今天上传发现所有的达成率全变成只有一位小数的了

![image](https://github.com/Diving-Fish/maimaidx-prober/assets/31172177/8b67917f-7f74-4dd7-988b-a19e0e203ea4)

**Comment by kuresaru** [comment]
本来说研究修一下 结果发现main分支里的prober1.3.0自己编译运行是好使的...

**Comment by Dreamail** [comment]
> 本来说研究修一下 结果发现main分支里的prober1.3.0自己编译运行是好使的...

用1.3.0上传查到的成绩正常？

**Comment by Diving-Fish** [comment]
个人界面关闭成绩掩码即可
