### ISSUE TITLE
查分器网站，rating计算器计算结果错误

### ISSUE THREAD

**Issue by lwxcd** [Diving-Fish/maimaidx-prober#119]
根据萌娘百科上的rating计算方法，目前的rating计算器与实际结果存在误差
如查分器计算出一首定数为13.0的曲子，其在100.4274%时达到290分，按萌娘百科的计算方法，实际上只能获得13.0*100.4274%*21.6=282分。

<img width="466" alt="{D721E651-C55C-4294-8D89-17F7B56EC10B}" src="https://github.com/Diving-Fish/maimaidx-prober/assets/60499101/97e64b7f-197e-4b76-981e-aa845ed2dc3b">
<img width="664" alt="{0DA9D400-7DA8-4be9-BC39-593773C6F5CF}" src="https://github.com/Diving-Fish/maimaidx-prober/assets/60499101/06ad2c34-6677-481d-befc-ed2d1d88e530">

**Comment by BiologyHazard** [comment]
![image](https://github.com/Diving-Fish/maimaidx-prober/assets/44924110/c543a449-3279-4d02-be3e-d20c3dba4526)
相同的问题，按照萌娘百科的 rating 计算方法，maimai 定数为 13.8 的乐曲，100.3087% → 299，99.9382% → 291。

**Comment by HighSierra0820** [comment]
浅看了一下上面两位的情况：
 - `13.0`的`100.4274%`是`282.0001392 `，`100.4273%`是`281.9998584 `；
 - `13.8`的`100.3087%`是`299.00017296`，`100.3086%`是`298.99987488`，`99.9382%`同理
 - 上述实际显示的rating是各系数段内最高值

注意到计算工具的三个选项卡第二个和第三个似乎没有大问题，只有第一个中rating计算结果偶尔有误，但达成率确实是rating变动的分界线，可能是二分环节出了差错；同时查看代码发现二分上限的设置似乎不妥（推测2500的意思是在相同系数达成率区间内rating最多跳动一次），或许可以改为区间内最大值（e.g. [100, 100.4999)中的100.4998）

https://github.com/Diving-Fish/maimaidx-prober/blob/4708aaab1baccb2f8f5052bacb28ddb442d82dbd/web/src/components/Calculators.vue#L675-L720

**Comment by kuresaru** [comment]
13.8定数100.0%到100.5%之间仍然计算错误

![Image](https://github.com/user-attachments/assets/79e737e3-b489-462f-b88e-f914effe147f)

![Image](https://github.com/user-attachments/assets/ed6d75a8-fc9e-4783-9b55-60e3d61e6d17)

![Image](https://github.com/user-attachments/assets/5c1fa511-60d1-48a3-8a6d-b9ffa17b6cc2)
