### ISSUE TITLE
[Feature request] 添加神将牌查漏补缺

### ISSUE THREAD

**Issue by Kotoki1337** [Diving-Fish/maimaidx-prober#12]
之前刷将牌的时候用贵项目的代理自己撸了一个简单的出来，但因为我不会 js 所以是 python 实现的，还考虑过用查分器导出的 `.csv` 文件来实现导出导入的查漏补缺，不过既然都直接用查分器的数据了，是不是直接内置进查分器更牛逼一点，但我不会 js 所以也发不出 pr，开个 issue 提一嘴问问想法。

**Comment by Diving-Fish** [comment]
已添加
