### ISSUE TITLE
中二节奏`music_data.json`中的乐曲标题与HTML中的不一致，导致分数导入失败

### ISSUE THREAD

**Issue by QingQiz** [Diving-Fish/maimaidx-prober#126]
具体来说：
- musicdata中的标题

  ![image](https://github.com/Diving-Fish/maimaidx-prober/assets/33107216/8ca5c67e-1c36-40d0-ac8f-c1f65bd30e0a)

- HTML中的标题

  ![image](https://github.com/Diving-Fish/maimaidx-prober/assets/33107216/0baf37fb-cbb0-4b61-a330-a056c322fe77)

**Comment by Diving-Fish** [comment]
这歌是所有难度都是这个title，还是只有黑谱是啊

**Comment by QingQiz** [comment]
我这边抓下来的HTML几个难度都是这个标题。

但据我所知，有一些人只是无法导入黑谱的成绩，，，我建议你在后台用sql查一下有多少人有这歌的成绩，

不行的话我建议给那个`md_title_map`的创建和查找都进行tolower/toupper处理

**Comment by Diving-Fish** [comment]
这个成绩比起其他的曲目非常少，总共只有 240 条记录，怀疑是某一个版本 sega 把这歌的歌名改掉了
后台改成大写了，担心直接改 case 会有 side effect，先看看能不能生效
