### ISSUE TITLE
[Bug] 因两首歌名相同导致无法正常导入两首歌曲的成绩

### ISSUE THREAD

**Issue by Kotoki1337** [Diving-Fish/maimaidx-prober#18]
### 公众号截图

![image](https://user-images.githubusercontent.com/35394151/134190402-5b4122cf-9379-4bbb-aa4e-38d8ffd8b9d3.png) ![image](https://user-images.githubusercontent.com/35394151/134191671-8d92ab71-7657-472e-ae76-c2b60d037413.png)

#### 导入后未全解

![image](https://user-images.githubusercontent.com/35394151/134192027-f4690a7c-d68f-479b-8a7d-bae092eda64c.png)

#### 全解后

![image](https://user-images.githubusercontent.com/35394151/134192162-8ea2cff1-bf2f-4f6c-9f0d-714fb5f9f0b3.png)

**Comment by Diving-Fish** [comment]
其实我记得解决过，但我再看看好了

**Comment by Diving-Fish** [comment]
已修复，现在CoF的Link会以Link(CoF)标识

**Comment by Kotoki1337** [comment]
![image](https://user-images.githubusercontent.com/35394151/149093576-4d20901f-0ebd-4d6e-8d80-99ecbfe8139c.png)

好像还是有问题
