### ISSUE TITLE
修改相对难度的批判标准及添加鸟歌难度标签

### ISSUE THREAD

**Issue by Pr0pHesyer** [Diving-Fish/maimaidx-prober#31]
相对难度由现行的
`
SSS及以上人数/总人数
`
改为
`
SS及以上人数/总人数
`

增加新tag：鸟歌难度
鸟歌难度公式为
`
SSS及以上人数/SS及以上人数
`

**Comment by Diving-Fish** [comment]
事实是 *SS的难度* 和 *从歌曲吃到分的难度* 完全是两个概念。查分器的相对难度初衷是评判是一首歌在同等难度下吃分的难易度，因此在DX 2021 更新以后从 SSS+ 调到了 SSS。
