### ISSUE TITLE
新版 Windows 微信默认不走系统代理，且代理程序可能崩溃

### ISSUE THREAD

**Issue by Merrg1n** [Diving-Fish/maimaidx-prober#35]
微信版本是 3.6.0.18，自动设置系统代理不再起效，需要手动在登录界面设置代理，如下图：
![image](https://user-images.githubusercontent.com/22628584/163430035-f164d595-95cf-446f-971f-6686c9ac8ef5.png)
这时候使用查分器查分 1.1.2 版本的查分器会报错
![_@7{9QD7W1F6MMLWHTKWVU6](https://user-images.githubusercontent.com/22628584/163430387-879d051a-e784-4949-9118-0825351b9cc4.png)
具体原因应该是这行 https://github.com/Diving-Fish/maimaidx-prober/blob/86ab087282304ea107bd1dee49f4cc3f39136510/proxy/cmd/maimaidx-prober-proxy/main.go#L131 的 `resp.Request` 可能为 `nil`，加了个 if 判断就可以解决该问题

**Comment by Diving-Fish** [comment]
直接发Pull request吧

**Comment by Merrg1n** [comment]
我自己测试改了这行是没有问题正常查分，但我加个 if 判断之后的版本发给别人用报了新错误，可能问题不止这些
![Q%KASAEK I8BY5X~DLCM$5M](https://user-images.githubusercontent.com/22628584/165115461-436a1719-5381-4192-a1b4-d440a0811654.png)
