### ISSUE TITLE
关于查分器对Proxifier等全局代理编辑器的支持

### ISSUE THREAD

**Issue by t-satoru** [Diving-Fish/maimaidx-prober#38]
首先感谢开发者的付出。
![image](https://user-images.githubusercontent.com/88642005/171666811-c921e0e8-190d-4d35-a8bd-4d869cb3c0b2.png)
因为我日常使用科学上网，所以安装了Proxifier以更方便地使某些不支持代理设置的软件走代理。
在使用查分器更新工具的时候，我也尝试了通过Proxifier来代理微信访问华立网站的流量，然而如图所示，没有任何反应。
先前我在macOS下使用更新工具的时候（那个时候macOS的查分器应该还不支持自动设置系统代理）甚至必须彻底退出Proxifier之后才能正常使用查分器，否则我连系统代理都无法手动设置。
所以，既然都是HTTPS代理，为什么不能通过Proxifier类第三方代理工具代理微信的流量，而只能通过设置系统代理实现？
因为每次更新查分器都必须退出Proxifier，导致了我的使用带来了一定程度的不便。
望尽快得到回复。
谢谢！

**Comment by Diving-Fish** [comment]
> 所以，既然都是HTTPS代理，为什么不能通过Proxifier类第三方代理工具代理微信的流量，而只能通过设置系统代理实现？

代理工具实际上做的是获取到代理的网页之后，对网页进行一系列操作最后转成分数。我猜测Proxifier这种强大的代理工具自然也可以设置代理规则来完成这一点，但这显然是给开发者增大工作量的行为。我们所做的所有工作都是为了降低门槛方便完全没有基础的用户使用，那么自然用 Windows 和 MacOS 的系统代理是门槛最低的，因为不需要安装任何额外的软件。

之后的更新预计也不会对第三方代理工具提供支持。
