### ISSUE TITLE
Windows 下的代理工具在提交 Basic 绿铺成绩时失败

### ISSUE THREAD

**Issue by bakapiano** [Diving-Fish/maimaidx-prober#39]
![screenshot](https://user-images.githubusercontent.com/29042285/173576471-209a6800-00c4-4ecd-a23f-d4706eb7ac0a.png)

HTTP 响应码为 500，其他平台未做测试；推测大概是后端上传接口的问题？

**Comment by Diving-Fish** [comment]
老毛病了。偶发性bug，没复现过，大概不影响使用
