### ISSUE TITLE
CHUNITHM 查分接口问题

### ISSUE THREAD

**Issue by QingQiz** [Diving-Fish/maimaidx-prober#50]
CHUNITHM 当前只提供了一个 `/chuni/query/player` 接口

做的bot想要一个查询所有成绩的接口，来实现一个成绩汇总的功能，如下图，图中是按等级汇总

[![image.png](https://i.postimg.cc/zBv743cd/image.png)](https://postimg.cc/R6rwHC9f)

maimai这个功能的实现是通过牌子查询拿到所有成绩的，不知道能否给CHUNITHM也添加一个类似的接口

**Comment by Diving-Fish** [comment]
Pull request (or wait) and ensure it will be only available to developers, refer to dev/player/records
Query plate is not standard and unsafe to user.

**Comment by QingQiz** [comment]
`dev/player/records` 需要token，如何获取呢，并没有在文档中看到

**Comment by Diving-Fish** [comment]
目前私聊我就行了，之后应该会在主页上添加个申请的页面。其实查plate那个之前就准备加developer限制了，但是感觉已经部署过的影响太大，就一直没推进

**Comment by QingQiz** [comment]
还有一个问题（off topic），我看 `dev/player/records` 的代码，似乎只能通过 `username` 查询，这表现在 bot 上就是查自己的也需要输一遍名字，这属于是 feature 还是 bug
