### ISSUE TITLE
代理程序在导入分数时报错

### ISSUE THREAD

**Issue by helloender** [Diving-Fish/maimaidx-prober#57]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xebc1e5]

goroutine 80 [running]:
main.commit({0xfd63e0?, 0xc000332500?})
        C:/Users/DivingFish/Github/maimaidx-prober/proxy/cmd/maimaidx-prober-proxy/main.go:71 +0x65
main.fetchData(0xc00025e100, {0xc00000a050, 0x1, 0x1})
        C:/Users/DivingFish/Github/maimaidx-prober/proxy/cmd/maimaidx-prober-proxy/main.go:102 +0x5e5
created by main.main.func2
        C:/Users/DivingFish/Github/maimaidx-prober/proxy/cmd/maimaidx-prober-proxy/main.go:223 +0x28f

**Comment by Choimoe** [comment]
请问解决了吗

这边遇到同样的问题，代码几乎完全一致

```
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xe8c1e5]

goroutine 68 [running]:
main.commit({0xfa63e0?, 0xc000210040?})
        C:/Users/DivingFish/Github/maimaidx-prober/proxy/cmd/maimaidx-prober-proxy/main.go:71 +0x65
main.fetchData(0xc000244100, {0xc000230008, 0x1, 0x1})
        C:/Users/DivingFish/Github/maimaidx-prober/proxy/cmd/maimaidx-prober-proxy/main.go:102 +0x5e5
created by main.main.func2
        C:/Users/DivingFish/Github/maimaidx-prober/proxy/cmd/maimaidx-prober-proxy/main.go:223 +0x28f
```

**Comment by Natsukawamasuzu** [comment]
同样的问题
<img width="729" alt="image" src="https://github.com/Diving-Fish/maimaidx-prober/assets/37575218/85b0ca5b-25e6-4c8f-aaaf-4b3d1f1a8f69">

**Comment by Diving-Fish** [comment]
最近一般是华立抽风 搞了半天返回了一坨错的html 比如502之类的 导致解析分数的API返回错误的内容以致报错 目前暂无解决办法
