### ISSUE TITLE
使用时提示 index out of range [0] with length 0

### ISSUE THREAD

**Issue by AkulaKirov** [Diving-Fish/maimaidx-prober#6]
问题描述: 使用代理后打开我的记录  代理报错  且数据未能同步
版本: maimaidx-prober-proxy-windows-1.1.1
复现: 按照使用教程操作  在电脑端微信打开我的记录
出现概率: 每次都是如此
log如下
`
登录成功，代理已开启到127.0.0.1:8033
代理设置已自动修改。
2021/04/25 23:28:21 http: panic serving 127.0.0.1:62981: runtime error: index out of range [0] with length 0
goroutine 52 [running]:
net/http.(*conn).serve.func1(0xc0000b2280)
        c:/go/src/net/http/server.go:1801 +0x147
panic(0x4940a0, 0xc0001adac0)
        c:/go/src/runtime/panic.go:975 +0x3e9
github.com/elazarl/goproxy.signHost(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/signer.go:44 +0xcce
github.com/elazarl/goproxy.TLSConfigFromCA.func1.1(...)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/https.go:434
github.com/elazarl/goproxy.TLSConfigFromCA.func1(0xc0001ada67, 0x15, 0xc00005f500, 0x0, 0x0, 0x0)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/https.go:439 +0x4e9
github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps(0xc000075860, 0x523c60, 0xc0001568c0, 0xc000168600)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/https.go:184 +0x5b5
github.com/elazarl/goproxy.(*ProxyHttpServer).ServeHTTP(0xc000075860, 0x523c60, 0xc0001568c0, 0xc000168600)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/proxy.go:114 +0xc9a
net/http.serverHandler.ServeHTTP(0xc000156700, 0x523c60, 0xc0001568c0, 0xc000168600)
        c:/go/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc0000b2280, 0x5243e0, 0xc00005cf00)
        c:/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2969 +0x36d
2021/04/25 23:29:08 [009] WARN: Error copying to client: readfrom tcp 127.0.0.1:8033->127.0.0.1:63006: read tcp 192.168.1.127:63007->192.30.255.112:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
`

**Comment by AkulaKirov** [comment]
我没装证书  我是铁憨憨

**Comment by Jack-Works** [comment]
```
2021/04/29 10:02:03 [008] INFO: Running 1 CONNECT handlers
2021/04/29 10:02:03 [008] INFO: on 0th handler: &{2 <nil> 0x7ff6319d7f20} maimai.wahlap.com:443
2021/04/29 10:02:03 [008] INFO: Assuming CONNECT is TLS, mitm proxying it
2021/04/29 10:02:03 [008] INFO: signing for maimai.wahlap.com
2021/04/29 10:02:03 http: panic serving 127.0.0.1:50533: runtime error: index out of range [0] with length 0
goroutine 56 [running]:
net/http.(*conn).serve.func1(0xc00005d9a0)
        c:/go/src/net/http/server.go:1801 +0x147
panic(0x7ff631a540a0, 0xc000177320)
        c:/go/src/runtime/panic.go:975 +0x3e9
github.com/elazarl/goproxy.signHost(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/signer.go:44 +0xcce
github.com/elazarl/goproxy.TLSConfigFromCA.func1.1(...)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/https.go:434
github.com/elazarl/goproxy.TLSConfigFromCA.func1(0xc0002022c7, 0x15, 0xc000210a80, 0x0, 0x0, 0x0)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/https.go:439 +0x4e9
github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps(0xc0000ba000, 0x7ff631ae3c60, 0xc0002221c0, 0xc000214300)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/https.go:184 +0x5b5
github.com/elazarl/goproxy.(*ProxyHttpServer).ServeHTTP(0xc0000ba000, 0x7ff631ae3c60, 0xc0002221c0, 0xc000214300)
        C:/Users/divingfish/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/proxy.go:114 +0xc9a
net/http.serverHandler.ServeHTTP(0xc0000c6000, 0x7ff631ae3c60, 0xc0002221c0, 0xc000214300)
        c:/go/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00005d9a0, 0x7ff631ae43e0, 0xc00020c4c0)
        c:/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2969 +0x36d
```

Having the same problem.

![image](https://user-images.githubusercontent.com/5390719/116494144-cd8b7780-a8d2-11eb-9b52-24477e9f7d8d.png)

I'm trying to run WeChat in the Windows Sandbox. The Root CA is installed in both the host and sandbox. But whatever I run this tool in host OS or sandbox, it always comes up with the error above.
