### ISSUE TITLE
查牌子时不知道哪些曲子是不需要打的

### ISSUE THREAD

**Issue by BiologyHazard** [Diving-Fish/maimaidx-prober#63]
如题，用query/plate查牌子时无法得知哪些曲子不用打，希望可以在api返回的数据中加入字段。
具体地，可以在music_data返回的数据中加入某个谱面属于哪些牌子。
比如，[{"id": ..., ..., "charts": [{"notes": ..., "charter": ..., "plates": ["真", "舞"]},...}...]

**Comment by Diving-Fish** [comment]
我也不知道
