### ISSUE TITLE
[bug] 本曲更高 DX Rating 未适配 新 Rating 计算方式

### ISSUE THREAD

**Issue by BiologyHazard** [Diving-Fish/maimaidx-prober#69]
![image](https://github.com/Diving-Fish/maimaidx-prober/assets/44924110/830eaa95-6103-4558-bc36-8c1161378e4c)

（
这里漏改了（

**Comment by xian2xian2** [comment]
计算工具 > RATING 线计算 也没适配到新计算方式
另据[考究](https://sgimera.github.io/mai_RatingAnalyzer/maidx_rating.html) ，部分卡 9 会有特殊的系数

**Comment by BiologyHazard** [comment]
感谢大佬
