### ISSUE TITLE
乐曲封面图片错误

### ISSUE THREAD

**Issue by Menci** [Diving-Fish/maimaidx-prober#82]
![image](https://github.com/Diving-Fish/maimaidx-prober/assets/11341955/ddc74742-06f8-4883-ae5c-16decdfea432)

如图所示，乐曲对应的封面图片展示错误，骸骨乐团（11045）的图片 URL 正确（https://www.diving-fish.com/covers/1045.png），但图片变成了另一张图片。

**Comment by BiologyHazard** [comment]
似乎是因为乐曲的id完全变了，而图片文件名还是老的ID

**Comment by BiologyHazard** [comment]
> 似乎是因为乐曲的id完全变了，而图片文件名还是老的ID

可以确认是这个原因，id11278原本是下克上上，现在是to the cosmic，
而to the cosmic点进封面是下克上上
