### ISSUE TITLE
关于导入方法 3 对目前的微信版本(半?)无效，以及查分器上的导入指南未及时更新

### ISSUE THREAD

**Issue by taranakineko** [Diving-Fish/maimaidx-prober#85]
关于导入方法三：微信目前使用了 xweb 内核，不使用 x5 内核
但 xweb 内核就目前来说没有 vConsole 调试功能，因此此方法算是半无效的了

至于查分器上的导入指南没更新这件事嘛......
主要是因为今天用代理工具导入的时候会卡在获取 Base 难度这一条提示
~~（不知道是网络原因还是咋的，在写这一条 issues 的时候竟然又能导入了...）~~
然后就尝试按照导入指南中的其他办法来尝试，那结果肯定是不行
~~翻到 https://github.com/Diving-Fish/maimaidx-prober/issues/65 后才发现仓库中的 README.md 已经对导入方法四进行补充，也对方法三中的代码进行更新~~
~~总之就是，（假装微笑）~~

顺带提一下，通过调试工具也可以走方法二的网页源代码获取
就是复制源代码有一点点点麻烦
~~在 Elements(元素) 选项卡中选中 `<html lang="zh"><head>` ，然后右键 Copy(复制)->Copy Elements(复制元素) 或者 Edit as HTML(编辑为 HTML) 后全选复制（~~

**Comment by YidaozhanYa** [comment]
目前可以使用 XPosed 模块 WebViewPP 来在新版微信里调出 vConsole，js 方法还是管用的，但是 DX 2023 的土豆服务器又卡又慢天天爆炸，点一下 OK 就没下文了

**Comment by taranakineko** [comment]
> 目前可以使用 XPosed 模块 WebViewPP 来在新版微信里调出 vConsole，js 方法还是管用的，但是 DX 2023 的土豆服务器又卡又慢天天爆炸，点一下 OK 就没下文了

~~土豆是这样，不如考来吃😋~~
虽说这方法对于无法解锁 bl 的手机用户来说有那么一点点的麻烦，或许可以考虑用小黄鸟什么的拿到网页源代码（好吧这方法也挺麻烦）

**Comment by YidaozhanYa** [comment]
README 里介绍的 Chrome DevTools 可以拿到源代码，然后直接传进查分器里。这是目前可用并且相对好用的方法之一。

**Comment by taranakineko** [comment]
> README 里介绍的 Chrome DevTools 可以拿到源代码，然后直接传进查分器里。这是目前可用并且相对好用的方法之一。

此方法已经在我一开始的 issue 中提及，在最后一段（
