### ISSUE TITLE
能否允许玩家导入分数时，跳过特定难度的谱面？

### ISSUE THREAD

**Issue by rabbitHog** [Diving-Fish/maimaidx-prober#88]
如题……每次导入的时候都得从绿谱开始，得等好久才能到紫谱白谱，对于b35地板13.3的玩家来讲，等待导入绿谱黄谱红谱的时间太漫长了而且还经常在导绿谱黄谱的时候直接报错退出

**Comment by xen0n** [comment]
人机交互方面需要设计。这些东西塞 `config.json` 合适还是命令行参数？我个人觉得 `config.json` 会好一点。

命令行参数也可以加，优先级比配置文件高。

```json
{"username": "xxx", "password": "xxx", "diffs_to_import": "expert,master,remaster"}
```

```sh
./maimaidx-prober-proxy -diffs-to-import expert,master,remaster
```

感觉 flag 名字可以 use some bikeshedding（
