### ISSUE TITLE
名牌板API问题

### ISSUE THREAD

**Issue by DoroWolf** [Diving-Fish/maimaidx-prober#90]
名牌板查询API无法查询以下的游玩目标和进度：
 - 华代（maimai でらっくす PLUS）
 - 煌代（maimai でらっくす Splash PLUS）
 - 星代（maimai でらっくす UNiVERSE PLUS）

它们对应的歌曲疑似与其上一代合并，导致无法查询。

**Comment by Diving-Fish** [comment]
国服特供，两个牌子一起跑完一起给，没有修改的打算
