### ISSUE TITLE
开启代理后网页端报错连接不安全

### ISSUE THREAD

**Issue by RabiHikari** [Diving-Fish/maimaidx-prober#92]
**问题描述**：正常启动PC微信，打开舞萌或中二的我的记录可以正常查看，但是一旦开启代理工具尝试查分，网页报错NET::ERR_CERT_AUTHORITY_INVALID，提示连接不是私密连接，并且点击高级按钮仍不能继续访问。同时代理工具内显示Cannot handshake client chunithm(_or maimai_).wahlap.com:443 remote error: tls: unknown certificate

网页一直是在用微信自带的浏览器打开。除代理工具查分外，其余两种方法（粘贴源代码和利用安卓手机导入）没有问题，但是导入教程仅针对舞萌，中二不知道怎么操作，希望补充。

**系统信息**：Windows 10 家庭中文版 21H2，微信版本3.9.5.81
![error](https://github.com/Diving-Fish/maimaidx-prober/assets/86303528/77226127-f4ba-4518-88ec-56ce70797ba6)

![error2](https://github.com/Diving-Fish/maimaidx-prober/assets/86303528/d394cf6d-f3e7-4623-998e-43ac464419ef)

**Comment by Diving-Fish** [comment]
<html>
<body>
<h4 tabindex="-1" dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 16px; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">1. 准备工作</h4><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">您可以访问<a href="https://github.com/Diving-Fish/maimaidx-prober/releases" style="box-sizing: border-box; background-color: transparent; color: var(--fgColor-accent, var(--color-accent-fg)); text-decoration: none;">此链接</a>来下载最新版本的代理工具，文件名为<strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">maimaidx-prober-proxy-(os).exe</strong>（os指您的操作系统）。</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">请将代理工具复制到一个空文件夹中，然后双击或使用控制台运行。初次运行后，代理工具将在当前目录下创建 3 个文件：</p>

文件名 | 说明
-- | --
config.json | 用户名和密码的配置文件
cert.crt | 可以导入的证书文件
key.pem | 私钥文件，无需进行任何操作

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">双击 cert.crt 文件打开，点击<strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">安装证书</strong>，打开证书导入向导。一般情况下，只需要对当前用户安装证书即可。之后点击下一步，按照如图选择将此证书放入“受信任的根证书颁发机构”进行存储。接下来，一路选择<strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">是</strong>，直到提示证书导入完成。</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/e9c48cd20ff7bb35c7ca3f2024175be6f4f490b24c058c6b54f2dd0a70f8f92f/68747470733a2f2f7777772e646976696e672d666973682e636f6d2f696d616765732f6d61696d616964782d70726f6265722f312e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--fgColor-accent, var(--color-accent-fg)); text-decoration: underline;"><img src="https://camo.githubusercontent.com/e9c48cd20ff7bb35c7ca3f2024175be6f4f490b24c058c6b54f2dd0a70f8f92f/68747470733a2f2f7777772e646976696e672d666973682e636f6d2f696d616765732f6d61696d616964782d70726f6265722f312e706e67" alt="" data-canonical-src="https://www.diving-fish.com/images/maimaidx-prober/1.png" style="box-sizing: content-box; border-style: none; max-width: 100%; background-color: var(--bgColor-default, var(--color-canvas-default));"></a></p>
</body>
</html>
