### ISSUE TITLE
功能请求：获取成绩时使用“未游玩乐曲除外”功能 / 分类搜索以减少等待时间

### ISSUE THREAD

**Issue by Amia33** [Diving-Fish/maimaidx-prober#94]
TL;DR Change `proxy/cmd/maimaidx-prober-proxy/prober_api.go` Line 104 when the default URL is not working.

```
Crawl URL Format:
https://maimai.wahlap.com/maimai-mobile/record/musicSort/search/?search=A&sort=1&playCheck=on&diff={0-4}
https://maimai.wahlap.com/maimai-mobile/record/musicSort/search/?search=G-{101-106}&sort=1&playCheck=on&diff={0-4}
```

受不了华立的土豆服务器了！（恼）
ci测试的时候发现夜间网络高峰期总会丢包 那么最简单的办法就是缩短要获取的列表 分多次进行获取
~~我认为增加timeout不是合理的解决办法(暴论)~~

单次测试结果:

<details>
<summary>ci-230706-21</summary>

genre
99  ERR    878

101 9.90s  51
102 51.13s 202
103 22.53s 124
104 43.50s 165
105 1.7min 251
106 35.24s 85
~4.4min

word:
0   52.30s 87
1   46.96s 69
2   35.59s 72
3   10.83s 65
4   6.14s  25
5   27.34s 67
6   29.28s 30
7   4.07s  15
8   5.44s  24
9   4.15s  8
10  52.82s 149
11  28.21s 112
12  28.42s 121
13  9.74s  30
14  2.46s  4
~5.7min

version
0   7.40s  42
1   5.68s  44
2   9.16s  56
3   11.15s 50
4   39.45s 29
5   13.88s 27
6   12.38s 33
7   8.10s  32
8   8.57s  42
9   22.72s 40
10  8.36s  41
11  4.70s  42
12  4.52s  46
13  26.78s 87
15  30.11s 95  
17  49.73s 130
19  8.77s  42
~4.5min

</details>

**Comment by bakapiano** [comment]
感觉也可以考虑用最近 50 首游玩记录的那个页面做增量更新

**Comment by Diving-Fish** [comment]
> 感觉也可以考虑用最近 50 首游玩记录的那个页面做增量更新，毕竟一天打满 50 局还是很难的hhhh

那个页面其实和拆分出来之后的差不多大了
