### ISSUE TITLE
[QUESTION] Doubting how long the token will expire. 

### ISSUE THREAD

**Issue by Dreamail** [Diving-Fish/maimaidx-prober#95]
如题
华立的token多久才会过期捏
目前只知道重新登录就会使旧token过期
但如果登录一次之后长时间不过期是否可以用于做好友机器人

**Comment by Dreamail** [comment]
Got it.
I found that the "_t" cookie after 1 year, which I have seen in Chrome cookie.
I have also confirm that it won't logout after an all night.

I'm working on a maimai bot. Thanks for your answer.

**Comment by Dreamail** [comment]
Does userid must be update during each request?
Or it can be used though a new userid was placed?

**Comment by Dreamail** [comment]
BTW, is the friendVS upload API deleted?
I can't post /page/friendVS.

**Comment by Dreamail** [comment]
Um, I meant diving-fish's scores upload api seems to be down. Scores page upload works but friend vs didn't.
I going to make a page-parser by myself.

**Comment by Diving-Fish** [comment]
> Um, I meant diving-fish's scores upload api seems to be down. Scores page upload works but friend vs didn't. I going to make a page-parser by myself.

Deployed.

**Comment by Dreamail** [comment]
> > Um, I meant diving-fish's scores upload api seems to be down. Scores page upload works but friend vs didn't. I going to make a page-parser by myself.
> 
> Deployed.

Oh, thanks.

**Comment by Dreamail** [comment]
Friend vs page parser seem to be broken. It update my records all 101%.
So I have make a parser myself, thanks for your work.
